name: Publish Package to npmjs
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Set Git Config
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com

      - name: NPM CI
        run: npm ci
      - name: Run Tests
        run: |
          npm test
      - name: Publish airview-aws-auth
        run: |
          npm version --no-git-tag-version  ${GITHUB_REF##*/}
          npm publish
